name: capnproto
description: Cap'n Proto is an extremely efficient protocol for sharing data and capabilities.
version: 0.2.0
homepage: https://github.com/JonasWanke/capnproto-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  basics: ^0.6.0
  collection: ^1.15.0
  dartx: ^0.7.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  test: ^1.17.3
  # test_coverage: ^0.5.0
