name: capnproto
description: Cap'n Proto is an extremely efficient protocol for sharing data and capabilities.
version: 0.2.0
homepage: https://github.com/JonasWanke/capnproto-dart

environment:
  sdk: ^3.4.2

dependencies:
  collection: ^1.15.0

dev_dependencies:
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: f493a5092722288669aca81decbf7b00f528adca
  test: ^1.17.3
