name: capnproto
description: Cap'n Proto is an extremely efficient protocol for sharing data and capabilities.
version: 0.2.0
homepage: https://github.com/JonasWanke/capnproto-dart

environment:
  sdk: ^3.4.2

dependencies:
  collection: ^1.15.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  test: ^1.17.3
