name: capnproto
description: Cap'n Proto is an extremely efficient protocol for sharing data and capabilities.
version: 0.1.0
homepage: https://github.com/JonasWanke/capnproto-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  basics: ^0.4.0
  collection: ^1.14.12
  dartx: ^0.5.0
  meta: ^1.1.8

dev_dependencies:
  extra_pedantic: ^1.2.0
  glados: ^0.4.0
  test: ^1.14.3
  test_coverage: ^0.5.0
