name: capnproto
description: Cap'n Proto is an extremely efficient protocol for sharing data and capabilities.
version: 0.2.0
repository: https://github.com/JonasWanke/capnproto-dart

environment:
  # When updating this, also update the matrixes in
  # `.github/workflows/build.yml`.
  sdk: ^3.6.0
resolution: workspace

dependencies:
  collection: ^1.15.0
  meta: ^1.16.0
  oxidized: ^6.2.0

dev_dependencies:
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 85282519bc847cf1a31ca4295f28b776de99c43c
  test: ^1.17.3
