// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by the capnpc-dart plugin to the Cap'n Proto schema compiler.
// Source: lib/src/schema/schema.capnp

import "package:capnproto/capnproto.dart" as $capnproto;
import "dart:core" as $core;
import "dart:typed_data" as $typed_data;
// struct Node.Parameter

// ignore: camel_case_types
final class Node_Parameter_Reader extends $capnproto.CapnpReader {
  const Node_Parameter_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();
}

// struct Node.NestedNode

// ignore: camel_case_types
final class Node_NestedNode_Reader extends $capnproto.CapnpReader {
  const Node_NestedNode_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();

  $core.int get id => reader.getUInt64(0, 0);
}

// struct Node.SourceInfo.Member

// ignore: camel_case_types
final class Node_SourceInfo_Member_Reader extends $capnproto.CapnpReader {
  const Node_SourceInfo_Member_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasDocComment => !reader.getPointerField(0).isNull;
  $core.String get docComment =>
      reader.getPointerField(0).getText(null).unwrap();
}

// struct Node.SourceInfo

// ignore: camel_case_types
final class Node_SourceInfo_Reader extends $capnproto.CapnpReader {
  const Node_SourceInfo_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);

  $core.bool get hasDocComment => !reader.getPointerField(0).isNull;
  $core.String get docComment =>
      reader.getPointerField(0).getText(null).unwrap();
}

// struct Node

// ignore: camel_case_types
final class Node_Reader extends $capnproto.CapnpReader {
  const Node_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);

  $core.bool get hasDisplayName => !reader.getPointerField(0).isNull;
  $core.String get displayName =>
      reader.getPointerField(0).getText(null).unwrap();

  $core.int get displayNamePrefixLength => reader.getUInt32(2, 0);

  $core.int get scopeId => reader.getUInt64(2, 0);

  void get file {}

  $core.bool get isGeneric => reader.getBool(288, false);
}

// struct Field

// ignore: camel_case_types
final class Field_Reader extends $capnproto.CapnpReader {
  const Field_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();

  $core.int get codeOrder => reader.getUInt16(0, 0);

  $core.int get discriminantValue => reader.getUInt16(1, 65535);
}

// struct Enumerant

// ignore: camel_case_types
final class Enumerant_Reader extends $capnproto.CapnpReader {
  const Enumerant_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();

  $core.int get codeOrder => reader.getUInt16(0, 0);
}

// struct Superclass

// ignore: camel_case_types
final class Superclass_Reader extends $capnproto.CapnpReader {
  const Superclass_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);
}

// struct Method

// ignore: camel_case_types
final class Method_Reader extends $capnproto.CapnpReader {
  const Method_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();

  $core.int get codeOrder => reader.getUInt16(0, 0);

  $core.int get paramStructType => reader.getUInt64(1, 0);

  $core.int get resultStructType => reader.getUInt64(2, 0);
}

// struct Type

// ignore: camel_case_types
final class Type_Reader extends $capnproto.CapnpReader {
  const Type_Reader(this.reader);

  final $capnproto.StructReader reader;

  void get void_ {}

  void get bool {}

  void get int8 {}

  void get int16 {}

  void get int32 {}

  void get int64 {}

  void get uint8 {}

  void get uint16 {}

  void get uint32 {}

  void get uint64 {}

  void get float32 {}

  void get float64 {}

  void get text {}

  void get data {}
}

// struct Brand.Scope

// ignore: camel_case_types
final class Brand_Scope_Reader extends $capnproto.CapnpReader {
  const Brand_Scope_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get scopeId => reader.getUInt64(0, 0);

  void get inherit {}
}

// struct Brand.Binding

// ignore: camel_case_types
final class Brand_Binding_Reader extends $capnproto.CapnpReader {
  const Brand_Binding_Reader(this.reader);

  final $capnproto.StructReader reader;

  void get unbound {}
}

// struct Brand

// ignore: camel_case_types
final class Brand_Reader extends $capnproto.CapnpReader {
  const Brand_Reader(this.reader);

  final $capnproto.StructReader reader;
}

// struct Value

// ignore: camel_case_types
final class Value_Reader extends $capnproto.CapnpReader {
  const Value_Reader(this.reader);

  final $capnproto.StructReader reader;

  void get void_ {}

  $core.bool get bool => reader.getBool(16, false);

  $core.int get int8 => reader.getInt8(2, 0);

  $core.int get int16 => reader.getInt16(1, 0);

  $core.int get int32 => reader.getInt32(1, 0);

  $core.int get int64 => reader.getInt64(1, 0);

  $core.int get uint8 => reader.getUInt8(2, 0);

  $core.int get uint16 => reader.getUInt16(1, 0);

  $core.int get uint32 => reader.getUInt32(1, 0);

  $core.int get uint64 => reader.getUInt64(1, 0);

  $core.double get float32 => reader.getFloat32(1, 0);

  $core.double get float64 => reader.getFloat64(1, 0);

  $core.bool get hasText => !reader.getPointerField(0).isNull;
  $core.String get text => reader.getPointerField(0).getText(null).unwrap();

  $core.bool get hasData => !reader.getPointerField(0).isNull;
  $typed_data.ByteData get data =>
      reader.getPointerField(0).getData(null).unwrap();

  $core.int get enum_ => reader.getUInt16(1, 0);

  void get interface_ {}
}

// struct Annotation

// ignore: camel_case_types
final class Annotation_Reader extends $capnproto.CapnpReader {
  const Annotation_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);
}

// enum ElementSize

enum ElementSize {
  empty(0),
  bit(1),
  byte(2),
  twoBytes(3),
  fourBytes(4),
  eightBytes(5),
  pointer(6),
  inlineComposite(7),
  notInSchema(null);

  const ElementSize(this.value);

  factory ElementSize.fromValue($core.int value) {
    return switch (value) {
      0 => ElementSize.empty,
      1 => ElementSize.bit,
      2 => ElementSize.byte,
      3 => ElementSize.twoBytes,
      4 => ElementSize.fourBytes,
      5 => ElementSize.eightBytes,
      6 => ElementSize.pointer,
      7 => ElementSize.inlineComposite,
      _ => ElementSize.notInSchema,
    };
  }

  final $core.int? value;
}

// struct CapnpVersion

// ignore: camel_case_types
final class CapnpVersion_Reader extends $capnproto.CapnpReader {
  const CapnpVersion_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get major => reader.getUInt16(0, 0);

  $core.int get minor => reader.getUInt8(2, 0);

  $core.int get micro => reader.getUInt8(3, 0);
}

// struct CodeGeneratorRequest.RequestedFile.Import

// ignore: camel_case_types
final class CodeGeneratorRequest_RequestedFile_Import_Reader
    extends $capnproto.CapnpReader {
  const CodeGeneratorRequest_RequestedFile_Import_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);

  $core.bool get hasName => !reader.getPointerField(0).isNull;
  $core.String get name => reader.getPointerField(0).getText(null).unwrap();
}

// struct CodeGeneratorRequest.RequestedFile

// ignore: camel_case_types
final class CodeGeneratorRequest_RequestedFile_Reader
    extends $capnproto.CapnpReader {
  const CodeGeneratorRequest_RequestedFile_Reader(this.reader);

  final $capnproto.StructReader reader;

  $core.int get id => reader.getUInt64(0, 0);

  $core.bool get hasFilename => !reader.getPointerField(0).isNull;
  $core.String get filename => reader.getPointerField(0).getText(null).unwrap();
}

// struct CodeGeneratorRequest

// ignore: camel_case_types
final class CodeGeneratorRequest_Reader extends $capnproto.CapnpReader {
  const CodeGeneratorRequest_Reader(this.reader);

  final $capnproto.StructReader reader;
}
